package com.sdata.ecommerce.mapper;

import com.sdata.ecommerce.domain.Category;
import com.sdata.ecommerce.domain.CategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdata_category
     *
     * @mbg.generated Wed Feb 13 22:59:13 CST 2019
     */
    long countByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdata_category
     *
     * @mbg.generated Wed Feb 13 22:59:13 CST 2019
     */
    int deleteByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdata_category
     *
     * @mbg.generated Wed Feb 13 22:59:13 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdata_category
     *
     * @mbg.generated Wed Feb 13 22:59:13 CST 2019
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdata_category
     *
     * @mbg.generated Wed Feb 13 22:59:13 CST 2019
     */
    int insertSelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdata_category
     *
     * @mbg.generated Wed Feb 13 22:59:13 CST 2019
     */
    List<Category> selectByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdata_category
     *
     * @mbg.generated Wed Feb 13 22:59:13 CST 2019
     */
    Category selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdata_category
     *
     * @mbg.generated Wed Feb 13 22:59:13 CST 2019
     */
    int updateByExampleSelective(@Param("record") Category record, @Param("example") CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdata_category
     *
     * @mbg.generated Wed Feb 13 22:59:13 CST 2019
     */
    int updateByExample(@Param("record") Category record, @Param("example") CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdata_category
     *
     * @mbg.generated Wed Feb 13 22:59:13 CST 2019
     */
    int updateByPrimaryKeySelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdata_category
     *
     * @mbg.generated Wed Feb 13 22:59:13 CST 2019
     */
    int updateByPrimaryKey(Category record);
}