package com.sdata.ecommerce.domain;

import com.sdata.ecommerce.domain.extended.ProductExtended;
import java.math.BigDecimal;

public class Product extends ProductExtended {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdata_product.id
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdata_product.name
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdata_product.keywords
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdata_product.parent_category
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    private String parentCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdata_product.manufacturer
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    private String manufacturer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdata_product.msrp
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    private BigDecimal msrp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdata_product.sale_price
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    private BigDecimal salePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdata_product.active_begin_date
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    private String activeBeginDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdata_product.active_end_date
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    private String activeEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdata_product.template
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    private String template;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdata_product.create_by
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdata_product.create_date
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    private String createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdata_product.update_by
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdata_product.update_date
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    private String updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdata_product.active
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    private Byte active;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdata_product.description
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdata_product.id
     *
     * @return the value of sdata_product.id
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdata_product.id
     *
     * @param id the value for sdata_product.id
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdata_product.name
     *
     * @return the value of sdata_product.name
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdata_product.name
     *
     * @param name the value for sdata_product.name
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdata_product.keywords
     *
     * @return the value of sdata_product.keywords
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdata_product.keywords
     *
     * @param keywords the value for sdata_product.keywords
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdata_product.parent_category
     *
     * @return the value of sdata_product.parent_category
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    public String getParentCategory() {
        return parentCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdata_product.parent_category
     *
     * @param parentCategory the value for sdata_product.parent_category
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    public void setParentCategory(String parentCategory) {
        this.parentCategory = parentCategory == null ? null : parentCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdata_product.manufacturer
     *
     * @return the value of sdata_product.manufacturer
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdata_product.manufacturer
     *
     * @param manufacturer the value for sdata_product.manufacturer
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer == null ? null : manufacturer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdata_product.msrp
     *
     * @return the value of sdata_product.msrp
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    public BigDecimal getMsrp() {
        return msrp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdata_product.msrp
     *
     * @param msrp the value for sdata_product.msrp
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    public void setMsrp(BigDecimal msrp) {
        this.msrp = msrp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdata_product.sale_price
     *
     * @return the value of sdata_product.sale_price
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    public BigDecimal getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdata_product.sale_price
     *
     * @param salePrice the value for sdata_product.sale_price
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    public void setSalePrice(BigDecimal salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdata_product.active_begin_date
     *
     * @return the value of sdata_product.active_begin_date
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    public String getActiveBeginDate() {
        return activeBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdata_product.active_begin_date
     *
     * @param activeBeginDate the value for sdata_product.active_begin_date
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    public void setActiveBeginDate(String activeBeginDate) {
        this.activeBeginDate = activeBeginDate == null ? null : activeBeginDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdata_product.active_end_date
     *
     * @return the value of sdata_product.active_end_date
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    public String getActiveEndDate() {
        return activeEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdata_product.active_end_date
     *
     * @param activeEndDate the value for sdata_product.active_end_date
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    public void setActiveEndDate(String activeEndDate) {
        this.activeEndDate = activeEndDate == null ? null : activeEndDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdata_product.template
     *
     * @return the value of sdata_product.template
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    public String getTemplate() {
        return template;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdata_product.template
     *
     * @param template the value for sdata_product.template
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    public void setTemplate(String template) {
        this.template = template == null ? null : template.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdata_product.create_by
     *
     * @return the value of sdata_product.create_by
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdata_product.create_by
     *
     * @param createBy the value for sdata_product.create_by
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdata_product.create_date
     *
     * @return the value of sdata_product.create_date
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdata_product.create_date
     *
     * @param createDate the value for sdata_product.create_date
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdata_product.update_by
     *
     * @return the value of sdata_product.update_by
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdata_product.update_by
     *
     * @param updateBy the value for sdata_product.update_by
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdata_product.update_date
     *
     * @return the value of sdata_product.update_date
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdata_product.update_date
     *
     * @param updateDate the value for sdata_product.update_date
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate == null ? null : updateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdata_product.active
     *
     * @return the value of sdata_product.active
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    public Byte getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdata_product.active
     *
     * @param active the value for sdata_product.active
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    public void setActive(Byte active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdata_product.description
     *
     * @return the value of sdata_product.description
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdata_product.description
     *
     * @param description the value for sdata_product.description
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdata_product
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Product other = (Product) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getKeywords() == null ? other.getKeywords() == null : this.getKeywords().equals(other.getKeywords()))
            && (this.getParentCategory() == null ? other.getParentCategory() == null : this.getParentCategory().equals(other.getParentCategory()))
            && (this.getManufacturer() == null ? other.getManufacturer() == null : this.getManufacturer().equals(other.getManufacturer()))
            && (this.getMsrp() == null ? other.getMsrp() == null : this.getMsrp().equals(other.getMsrp()))
            && (this.getSalePrice() == null ? other.getSalePrice() == null : this.getSalePrice().equals(other.getSalePrice()))
            && (this.getActiveBeginDate() == null ? other.getActiveBeginDate() == null : this.getActiveBeginDate().equals(other.getActiveBeginDate()))
            && (this.getActiveEndDate() == null ? other.getActiveEndDate() == null : this.getActiveEndDate().equals(other.getActiveEndDate()))
            && (this.getTemplate() == null ? other.getTemplate() == null : this.getTemplate().equals(other.getTemplate()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getActive() == null ? other.getActive() == null : this.getActive().equals(other.getActive()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdata_product
     *
     * @mbg.generated Mon Feb 18 11:47:42 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getKeywords() == null) ? 0 : getKeywords().hashCode());
        result = prime * result + ((getParentCategory() == null) ? 0 : getParentCategory().hashCode());
        result = prime * result + ((getManufacturer() == null) ? 0 : getManufacturer().hashCode());
        result = prime * result + ((getMsrp() == null) ? 0 : getMsrp().hashCode());
        result = prime * result + ((getSalePrice() == null) ? 0 : getSalePrice().hashCode());
        result = prime * result + ((getActiveBeginDate() == null) ? 0 : getActiveBeginDate().hashCode());
        result = prime * result + ((getActiveEndDate() == null) ? 0 : getActiveEndDate().hashCode());
        result = prime * result + ((getTemplate() == null) ? 0 : getTemplate().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getActive() == null) ? 0 : getActive().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        return result;
    }
}