package com.sdata.ecommerce.domain;

public class ProductImage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_image.id
     *
     * @mbg.generated Tue Feb 19 08:49:00 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_image.product_id
     *
     * @mbg.generated Tue Feb 19 08:49:00 CST 2019
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_image.title
     *
     * @mbg.generated Tue Feb 19 08:49:00 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_image.path
     *
     * @mbg.generated Tue Feb 19 08:49:00 CST 2019
     */
    private String path;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_image
     *
     * @mbg.generated Tue Feb 19 08:49:00 CST 2019
     */
    public ProductImage(String id, String productId, String title, String path) {
        this.id = id;
        this.productId = productId;
        this.title = title;
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_image
     *
     * @mbg.generated Tue Feb 19 08:49:00 CST 2019
     */
    public ProductImage() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_image.id
     *
     * @return the value of product_image.id
     *
     * @mbg.generated Tue Feb 19 08:49:00 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_image.id
     *
     * @param id the value for product_image.id
     *
     * @mbg.generated Tue Feb 19 08:49:00 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_image.product_id
     *
     * @return the value of product_image.product_id
     *
     * @mbg.generated Tue Feb 19 08:49:00 CST 2019
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_image.product_id
     *
     * @param productId the value for product_image.product_id
     *
     * @mbg.generated Tue Feb 19 08:49:00 CST 2019
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_image.title
     *
     * @return the value of product_image.title
     *
     * @mbg.generated Tue Feb 19 08:49:00 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_image.title
     *
     * @param title the value for product_image.title
     *
     * @mbg.generated Tue Feb 19 08:49:00 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_image.path
     *
     * @return the value of product_image.path
     *
     * @mbg.generated Tue Feb 19 08:49:00 CST 2019
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_image.path
     *
     * @param path the value for product_image.path
     *
     * @mbg.generated Tue Feb 19 08:49:00 CST 2019
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_image
     *
     * @mbg.generated Tue Feb 19 08:49:00 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ProductImage other = (ProductImage) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getPath() == null ? other.getPath() == null : this.getPath().equals(other.getPath()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_image
     *
     * @mbg.generated Tue Feb 19 08:49:00 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getPath() == null) ? 0 : getPath().hashCode());
        return result;
    }
}