spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_sample?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5 #Minimal idle connection
      maximum-pool-size: 10 #Max connection num
      pool-name: ecommerce-pool #pool name
      connection-timeout: 30000 #connection timeout



mybatis:
  type-aliases-package: com.sdata.ecommerce.domain #Domain Classes Package
  mapper-locations: classpath:/mybatis/mapper/*.xml #Mapper Locations

# Pagination
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql