spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_sample?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      # 最小的连接池数量。为了高峰的性能和相应，一般设成同（maximum-pool-size）一样。
      minimum-idle: 10
      # 连接池中最大的的连接数，一个MySQL实例最多允许几百个连接（max_connections），请不要设的过大。如果大量连接未正常关闭，将会在一段时间内（wait_timeout）无连接可用。
      maximum-pool-size: 10
      # 连接池的名字
      pool-name: ecommerce-pool
      # 只读数据库时设为True
      read-only: false
      # 连接的最长存活时间。max-lifetime 和 idle-timeout 最好设置小于（wait_timeout）数分钟，防止mysql关闭连接。
      max-lifetime: 600000
      # 默认为600000ms（10分钟）,有且仅当minimum-idle 小于 maximum-pool-size，这个参数才生效去移除超过idleTimeout 的连接.
      idle-timeout: 600000
      # SQL 客户端从连接池中获取连接的超时时间，如果超时，将会抛出SQLException
      connection-timeout: 30000
  servlet:
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB

mybatis:
  # Domain 类路径
  type-aliases-package: com.sdata.ecommerce.domain
  # Mapper XML 路径
  mapper-locations: classpath:/mybatis/mapper/*.xml, classpath:/mybatis/mapper/extended/*.xml

fdfs:
  # 读取超时
  so-timeout: 1500
  # 连接超时
  connect-timeout: 1000
  # 缩略图参数
  thumb-image:
    width: 150
    height: 150
  # tracker 列表
  tracker-list:
    192.168.99.167:22122